# Generated by Django 3.0.8 on 2020-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_netatmo_temp_dec'),
    ]

    operations = [
        migrations.AddField(
            model_name='netatmo',
            name='humidity_dec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
