# Generated by Django 3.0.8 on 2020-07-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_netatmo_humidity_dec'),
    ]

    operations = [
        migrations.AddField(
            model_name='netatmo',
            name='rec_time',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
    ]
