# Generated by Django 3.0.8 on 2020-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_netatmo_rec_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hochbeet2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_time', models.DateTimeField(auto_now_add=True)),
                ('light', models.DecimalField(decimal_places=1, max_digits=5)),
                ('battery', models.DecimalField(decimal_places=1, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('conductivity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('moisture', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
