# Generated by Django 3.0.8 on 2020-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20200708_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hochbeet2',
            name='battery',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hochbeet2',
            name='conductivity',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hochbeet2',
            name='light',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hochbeet2',
            name='moisture',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hochbeet2',
            name='temperature',
            field=models.CharField(max_length=15),
        ),
    ]
