# Generated by Django 2.2.28 on 2023-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20200708_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Netatmo',
        ),
    ]
