# Generated by Django 2.2.28 on 2023-04-01 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_testperson_rec_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testperson',
            name='pers_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
